### PR TITLE
April Meetup Recap

### PR DESCRIPTION
**Pull request by EdTechChris**
created April Meetup Recap and edited the April Meetup title so files would be in a better order.

### CODE REVIEW

**Comment by EdTechChris** [comment]
updated and cleaned up links

**Review by smashism — CHANGES_REQUESTED** [review]
The link at the end of the Data Dog resources needs to be fixed, there is a stray colon, no space, and a missing period at the end of the sentence.

**Comment by EdTechChris** [comment]
Thanks. Made the changes.

**Review by smashism — CHANGES_REQUESTED** [review]
Can we make the resources into an unordered list? This is pretty easy in markdown, just add a `-` or a `*` at the beginning of each line.

**Comment by EdTechChris** [comment]
Changed formatting to bulleted list on web links.

**Pull request closed without merging**
